"""Add Analyzed URLs Table

Revision ID: 4c6066caa8a9
Revises: 1c7cf2506ceb
Create Date: 2025-06-30 18:12:23.853647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4c6066caa8a9'
down_revision: Union[str, None] = '1c7cf2506ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analyzed_created_at', 'analyzed_urls', ['created_at'], unique=False)
    op.create_index('idx_analyzed_processed', 'analyzed_urls', ['processed'], unique=False)
    op.create_index('idx_analyzed_processed_created', 'analyzed_urls', ['processed', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analyzed_processed_created', table_name='analyzed_urls')
    op.drop_index('idx_analyzed_processed', table_name='analyzed_urls')
    op.drop_index('idx_analyzed_created_at', table_name='analyzed_urls')
    op.drop_table('analyzed_urls')
    # ### end Alembic commands ###
