"""Add is_active column to URL

Revision ID: f751ba1d4b7d
Revises: 
Create Date: 2025-06-04 20:26:47.692442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f751ba1d4b7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('urls', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_urls_priority', table_name='urls')
    op.drop_index('idx_urls_status', table_name='urls')
    op.drop_constraint('urls_url_source_key', 'urls', type_='unique')
    op.create_unique_constraint('uix_url_source', 'urls', ['url', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_url_source', 'urls', type_='unique')
    op.create_unique_constraint('urls_url_source_key', 'urls', ['url', 'source'])
    op.create_index('idx_urls_status', 'urls', ['status'], unique=False)
    op.create_index('idx_urls_priority', 'urls', ['priority'], unique=False)
    op.alter_column('urls', 'meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('urls', 'is_active')
    # ### end Alembic commands ###
