services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data: