"""
http://rss.cnn.com/rss/cnn_topstories.rss
https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
https://feeds.washingtonpost.com/rss/national
https://feeds.nbcnews.com/nbcnews/public/news
https://abcnews.go.com/abcnews/topstories
https://www.cbsnews.com/latest/rss/main
https://rssfeeds.usatoday.com/usatoday-NewsTopStories
https://www.npr.org/rss/rss.php?id=1001
https://feeds.reuters.com/reuters/topNews
https://feeds.foxnews.com/foxnews/latest
http://feeds.bbci.co.uk/news/world/rss.xml
https://www.aljazeera.com/xml/rss/all.xml
https://www.theguardian.com/world/rss
https://rss.dw.com/rdf/rss-en-all
https://www.france24.com/en/rss
https://www.cbc.ca/cmlink/rss-world
"""